# questions.py — Barcha 300 ga yaqin biologiya savollari bazasi

BIOLOGY_QUESTIONS = [
    # --- 1-QISM: Boshlang'ich va Asosiy savollar ---
    {"q": "Genetikada 'Codominantlik' holatida geterozigota fenotipi qanday namoyon bo'ladi?", "o": ["Ikkala allelning ham to'liq va bir paytda namoyon bo meyorida", "Aralash (oraliq) fenotip paydo bo'lishi bilan", "Faqat retsessiv belgi namoyon bo'lishi bilan", "Birinchi allelning butunlay yo'qolishi bilan"], "c": 0},
    {"q": "Eukariotlarda rRNK ning ko'pchilik turlari (18S, 28S, 5.8S) yadrocha sohasida qaysi ferment orqali transkripsiyalanadi?", "o": ["RNK-polimeraza I", "RNK-polimeraza II", "RNK-polimeraza III", "DNK-polimeraza alpha"], "c": 0},
    {"q": "Buyrak yetishmovchiligida gemodializ apparatida qon qaysi tamoyil bo'yicha tozalanadi?", "o": ["Yarim o'tkazgich membrana orqali diffuziya va dializ", "Faol transport va ATF sari", "Fagotsitoz jarayoni", "Gidroliz reaksiyasi"], "c": 0},
    {"q": "Qon plazmasidagi osmolyarlikni va onkotik bosimni saqlashda eng katta rol o'ynaydigan oqsil qaysi?", "o": ["Albumin", "Fibrinogen", "Gammaglobulin", "Protrombin"], "c": 0},
    {"q": "Sutemizuvchilar tuxum hujayrasini o'rab turuvchi shaffof parda nima deyiladi?", "o": ["Zona pellucida", "Corona radiata", "Vitellin parda", "Xorion"], "c": 0},
    {"q": "Mitoxondriya ichki membranasi bo'ylab protonlar (H+) harakatida ATF sintez qiluvchi kompleks nima deyiladi?", "o": ["F0F1-ATF-sintaza", "NADH-degidrogenaza", "SitoXrom c-oksidaza", "Suksinatdegidrogenaza"], "c": 0},
    {"q": "O'simliklarda barg to'kilishi va meva uzilishida hujayra devorini parchalovchi fermentlar qaysi gormon ta'sirida faollashadi?", "o": ["Etilen va Absiz kislotasi", "Auksin va Gibberellin", "Sitokinin va Auksin", "Brassinosteroidlar"], "c": 0},
    {"q": "Sitogenetik usulda inson xromosomalari qaysi fazada fiksatsiya qilinadi va tahlil etiladi?", "o": ["Metafaza bosqichida (Kolxitsin qo'llab)", "Profaza bosqichida", "Telofaza bosqichida", "Interfazaning G1 davrida"], "c": 0},
    {"q": "Hujayra siklining G1 va G2 davrlarida nima sodir bo'ladi?", "o": ["G1 - oqsil va RNK sintezi, o'sish; G2 - bo'linishga tayyorgarlik", "G1 - DNK replikatsiyasi; G2 - xromosoma ajralishi", "G1 - yadro parda yo'qolishi; G2 - sentriolalar ajralishi", "Ikkala davrda ham faqat ATF parchalanadi"], "c": 0},
    {"q": "Inson orqa miyasining oldingi shoxlarida joylashgan neyronlar qanday vazifani bajaradi?", "o": ["Harakatlantiruvchi (Motor) neyronlar", "Sezuvchi (Sensorig) neyronlar", "Qo'shimcha (Kirituvchi) neyronlar", "Vegetativ simpatik neyronlar"], "c": 0},
    {"q": "O'simliklarda ikkilamchi ksilema va floema nimadan hosil bo'ladi?", "o": ["Kambiy to'qimasidan", "Protodermadan", "Asosiy meristemadan", "Peritsikldan"], "c": 0},
    {"q": "Prokariotlarda DNK transkripsiyasini boshlash uchun RNK-polimerazaga qaysi omil (subbirlik) birikishi kerak?", "o": ["Sigma-omil (σ-factor)", "Rho-omil (ρ-factor)", "TATA-fakor", "TIF2-omil"], "c": 0},
    {"q": "Eukariotlarda gen ekspressiyasining eng birinchi darajadagi boshqarilishi qayerda kechadi?", "o": ["Xromatin modifikatsiyasi (Asetillanish va Metillanish) darajasida", "Splaysing darajasida", "Translyatsiya darajasida", "Post-translyatsiya darajasida"], "c": 0},
    {"q": "Genetikada 'Maternal effekt' (onadorlik effekti) nimaga bog'liq?", "o": ["Tuxum hujayra sitoplazmasida to'plangan mRNK va oqsillarga", "Yadroviy genlar o'zaro birikishiga", "Otadan o'tadigan Y-xromosomaga", "Faqat atrof-muhit haroratiga"], "c": 0},
    {"q": "Qaysi xromosoma mutatsiyasida xromosomaning muayyan qismi 180 darajaga burilib qayta birikadi?", "o": ["Inversiya", "Duplikatsiya", "Deletsiya", "Translokatsiya"], "c": 0},
    {"q": "Nerv tolasida Mielin qobig'ini periferik nerv sistemasida qaysi hujayralar hosil qiladi?", "o": ["Shvann hujayralari (Lemmotsitlar)", "Oligodendrotsitlar", "Astrotsitlar", "Mikrogiya hujayralari"], "c": 0},
    {"q": "Sutemizuvchilar o'pkasida gaz almashinuvi kechadigan asosiy struktur birlik?", "o": ["Alveolalar", "Bronxiolalar", "Tratheyalar", "Plevra bo'shlig'i"], "c": 0},
    {"q": "Glukoneogenez jarayonida piruvatdan oksaloatsetat hosil qiluvchi ferment qaysi?", "o": ["Piruvatkarboksilaza", "Piruvatkinaza", "Laktatdegidrogenaza", "Fosfoenolpiruvatkarboksikinaza"], "c": 0},
    {"q": "Bakteriyalarda peptidoglikan (murein) sintezini tormozlovchi va ularni parchalovchi antibiotik guruh?", "o": ["Penitsillinlar va Tsefalosporinlar", "Tetratsiklinlar", "Streptomitsinlar", "Xloramfenikol"], "c": 0},
    {"q": "Yurak siklining umumiy pauza (bo'lmacha va qorinchalar diastolasi) davri qancha davom etadi?", "o": ["0.4 sekund", "0.1 sekund", "0.3 sekund", "0.8 sekund"], "c": 0},

    # --- 2-QISM: Chuqurlashtirilgan savollar ---
    {"q": "Genetikada 'epistaz' hodisasi nimani anglatadi?", "o": ["Bir genning boshqa alel bo'lmagan gen ta'sirini bostirishini", "Ikkita alel genning teng namoyon bo'lishini", "Bitta genning bir nechta belgilarga ta'sir ko'rsatishini", "Xromosomalarning o'zaro almashinishini"], "c": 0},
    {"q": "Plazmoliz jarayoni o'simlik hujayrasida qachon kuzatiladi?", "o": ["Hujayra gipertonik eritmaga tushganda", "Hujayra gipotonik eritmaga tushganda", "Hujayra izotonik eritmaga tushganda", "Distillangan suvga solinganda"], "c": 0},
    {"q": "O'simliklarda florigen gormoni qayerda sintezlanadi?", "o": ["Barglarda", "Ildiz uchida", "Meva po'stida", "Tugunchada"], "c": 0},
    {"q": "DNK zanjirida Timin (T) o'rnini RNKda qaysi azotli asos egallaydi?", "o": ["Urasil", "Adenin", "Sitozin", "Guanin"], "c": 0},
    {"q": "Oksidlanishli fosforillanish bosqichida bir molekula NADH2 dan necha molekula ATF hosil bo'ladi?", "o": ["2.5 (yoki 3)", "1.5 (yoki 2)", "36", "38"], "c": 0},
    {"q": "Bakteriofaglar bu — ...", "o": ["Bakteriyalarni zararlaydigan viruslar", "Fagotsitoz qiluvchi bakteriyalar", "Zamburug' sporalari", "Bir hujayrali sodda hayvonlar"], "c": 0},
    {"q": "Inson qonidagi leykotsitlar orasida eng ko'p ulushni qaysilari egallaydi?", "o": ["Neytrofillar", "Limfotsitlar", "Monotsitlar", "Eozinofillar"], "c": 0},
    {"q": "Sikloz (sitoplazmaning harakati) eukariot hujayrada qaysi strukturalar orqali ta'minlanadi?", "o": ["Mikrofilamentlar va mikrotsayroqlar", "Lizosomalar", "Yadro pardasi", "Ribosomalar"], "c": 0},
    {"q": "Fotosintezning yorug'lik bosqichida suv fotolizi natijasida qaysi gaz ajraladi?", "o": ["Kislorod (O2)", "Karbonat angidrid (CO2)", "Azot (N2)", "Vodorod (H2)"], "c": 0},
    {"q": "Genom mutatsiyasiga misol bo'la oladigan holat qaysi?", "o": ["Aneuploidiya (Xromosomalar sonining o'zgarishi)", "Inversiya", "Translokatsiya", "Nuqtali mutatsiya"], "c": 0},
    {"q": "Buyrak yetishmovchiligida qonda qaysi modda miqdori keskin oshib ketadi?", "o": ["Mochevina va kreatinin", "Glyukoza", "Globin", "Bilirubin"], "c": 0},
    {"q": "T-Xelper leykotsitlarining asosiy vazifasi nima?", "o": ["B-limfotsitlar va T-killerlarni faollashtirish", "Antitelolar sintez qilish", "Fagotsitoz o'tkazish", "Gistamin ajratish"], "c": 0},
    {"q": "Fotosintezning C3 va C4 yo'llari orasidagi asosiy farq nimada?", "o": ["C4 o'simliklarida CO2 dastlab 4 uglerodli kislotaga birikadi", "C3 o'simliklarida yorug'lik bosqichi bo'lmaydi", "C4 o'simliklarida suv fotolizi kechmaydi", "C3 o'simliklari faqat tunda ishlaydi"], "c": 0},
    {"q": "Poliploidiya hodisasi ko'proq qaysi organizmlarda uchraydi va ijobiy natija beradi?", "o": ["O'simliklarda", "Odamlarda", "Sutemizuvchilarda", "Qushlarda"], "c": 0},
    {"q": "Eukariotlarda transkripsiya jarayoni qayerda kechadi?", "o": ["Yadroda", "Sitoplazmada", "Ribosomada", "Golji majmuasida"], "c": 0},
    {"q": "Inson yuragining chap qorinchasidan qaysi qon tomiri chiqadi?", "o": ["Aorta", "O'pka arteriyasi", "Yuqori kovak vena", "Pastki kovak vena"], "c": 0},
    {"q": "Nukleotidlar bir-biri bilan qanday kimyoviy bog' orqali bog'lanib zanjir hosil qiladi?", "o": ["Fosfodieter bog'", "Vodorod bog'", "Peptid bog'", "Disulfid bog'"], "c": 0},
    {"q": "Mitoxondriya va xloroplastlarning kelib chiqishi bo'yicha 'Simbioz nazariya'si nimani ta'kidlaydi?", "o": ["Ular eukariot hujayra ichiga kirib qolgan qadimiy prokariotlardir", "Ular yadro pardasidan hosil bo'lgan", "Ular lizosomadan rivojlangan", "Ular bir hujayrali zamburug'lardir"], "c": 0},
    {"q": "Sitokinlar immun tizimida qanday vazifani bajaradi?", "o": ["Hujayralararo signal beruvchi molekulalar", "Antitelo va antigen kompleksini parchalovchilar", "Kislorod tashuvchilar", "DNK ko'paytiruvchilar"], "c": 0},

    # --- 3-QISM: Murakkab va Olimpiada savollari ---
    {"q": "Fotosintezning yorug'lik reaksiyalarida e- o'tkazuvchi Z-sxema bo'ylab electron qayerdan qayerga uzatiladi?", "o": ["Suvdan NADP+ ga", "NADP+ dan suvga", "CO2 dan glyukozaga", "ATF dan xlorofillga"], "c": 0},
    {"q": "O'simliklarda 'Guttatsiya' hodisasi nima va u qaysi a'zo orqali kechadi?", "o": ["Suyuq suv tomchilarining gidatodalar (suv teshikchalari) orqali ajralishi", "Bug' holatidagi suvning ustitsadan chiqishi", "Shira ajralishi", "Ildiz orqali suv so'rilishi"], "c": 0},
    {"q": "Odam organizmida qon hosil bo'lishi (Gematopoez) katta yoshlilarda qayerda kechadi?", "o": ["Qizil suyak ko'migida", "Sariq suyak ko'migida", "Jigarda", "Taloq pulpasida"], "c": 0},
    {"q": "Xromosomaning sentromera sohasida joylashgan va bo'linish urchug'i iplari birikadigan oqsilli disk?", "o": ["Kinetoxor", "Nukleosoma", "Telomera", "Astrotsit"], "c": 0},
    {"q": "Prion kasalliklariga misol bo'ladigan xastalikni toping.", "o": ["Kreytsfeldt-Yakob kasalligi va Kuru", "Altsgeymer kasalligi", "Parkinson kasalligi", "Huntington kasalligi"], "c": 0},
    {"q": "DNK molekulasida Guanin (G) va Sitozin (S) orasida nechta vodorod bog'i bo'ladi?", "o": ["3 ta vodorod bog'i", "2 ta vodorod bog'i", "1 ta vodorod bog'i", "4 ta vodorod bog'i"], "c": 0},
    {"q": "Inson ko'zidagi to'r pardada joylashgan 'Sariq dog' (Fovea centralis) sohasida qaysi retseptorlar ko'p bo'ladi?", "o": ["Faqat kolbachasimon hujayralar (Kolbochkalar)", "Faqat tayyoqchasimon hujayralar", "Ikkalasi ham teng", "Retseptorlar bo'lmaydi"], "c": 0},
    {"q": "Oqsillarning uchlamchi va to'rtlamchi strukturasi buzilishi lekin birinchi darajali peptid bog'ining saqlanib qolishi nima deyiladi?", "o": ["Qaytuvchan denaturatsiya", "Qaytmas denaturatsiya", "Renaturatsiya", "Proteoliz"], "c": 0},
    {"q": "Restriksiya fermentlari yordamida kesilgan DNK bo'laklarining yopishqoq uchlari qanday xususiyatga ega?", "o": ["Komplementar bir zanjirli ketma-ketlikka ega bo'ladi", "To'g'ri (kallakli) kesilgan bo'ladi", "Faqat A-T juftliklaridan iborat bo'ladi", "Faqat RNK dan iborat bo'ladi"], "c": 0},
    {"q": "Bakteriyalarning sporasi nima uchun xizmat qiladi?", "o": ["Noqulay atrof-muhit sharoitlaridan saqlanish uchun", "Ko'payish va tarqalish uchun", "Oziq-ovqat zaxirasini to'plash uchun", "Hujayralararo aloqa uchun"], "c": 0},
    {"q": "Krebss siklida hosil bo'ladigan va nafas olish zanjiriga uzatiladigan qaytarilgan kofermentlar qaysilar?", "o": ["NADH va FADH2", "NADP H va ATF", "Piruvat va Laktat", "KoA va Atsetat"], "c": 0},
    {"q": "Autofagosoma bilan lizosoma qo'shilishi natijasida hosil bo'ladigan organoid?", "o": ["Autolizosoma (Autofagolizosoma)", "Peroksisoma", "Birlamchi lizosoma", "Geterofagosoma"], "c": 0},
    {"q": "Inson miyasining qaysi bo'limida nafas olish, yutish va qon tomirlar markazi joylashgan?", "o": ["Uzunchoq miyada (Medulla oblongata)", "Miyachada", "O'rta miyada", "Oraliq miyada"], "c": 0},
    {"q": "O'simliklarda 'Tropizm' va 'Nastiya' harakatlarining asosiy farqi nimada?", "o": ["Tropizm - yo'naltirilgan ta'sirga javob; Nastiya - yo'nalishsiz ta'sirga javob", "Tropizm - tez harakat; Nastiya - sekin harakat", "Tropizm - faqat ildizda; Nastiya - faqat mevalarda", "Ikkalasi ham bir xil jarayon"], "c": 0},
    {"q": "Gipofiz bezining orqa bo'lagidan ajraladigan Vasopressin (Antidiuretik gormon - ADG) ning asosiy funksiyasi?", "o": ["Buyrak nefronlarida suv reabsorbsiyasini oshirish", "Siydik miqdorini ko'paytirish", "Qonda kalsiyni kamaytirish", "Glikogen sintezini tezlashtirish"], "c": 0},
    {"q": "Viruslar hujayraga kirganda ularning kapsid oqsillaridan xalos bo'lishi nima deyiladi?", "o": ["Yechilish (Uncoating)", "Adsorbsiya", "Penetratsiya", "Maturatsiya"], "c": 0},
    {"q": "Polimeraza zanjir reaksiyasida (PZR) DNK zanjirlarini ajratish uchun qanday harorat qo'llaniladi?", "o": ["94-95 °C (Denaturatsiya bosqichi)", "50-60 °C", "72 °C", "37 °C"], "c": 0},
    {"q": "Odam so'lagida joylashgan va kraxmalni disaxaridlarga parchalovchi ferment?", "o": ["Ptiyalin (Tuklik alfa-amilaza)", "Pepsin", "Tiripsin", "Lipaza"], "c": 0},
    {"q": "O'simliklarda murtak xaltasi (megasporogenez) natijasida necha o'zakli struktura hosil bo'ladi?", "o": ["8 o'zakli murtak xaltasi", "4 o'zakli murtak xaltasi", "2 o'zakli murtak xaltasi", "16 o'zakli murtak xaltasi"], "c": 0},
    {"q": "Meyozda krossingover kechgandan so'ng gomologik xromosomalarning bir-biriga teshilishi/birikib turish nuqtasi nima deyiladi?", "o": ["Xiazma", "Sentromera", "Kinetoxor", "Nukleosoma"], "c": 0},
    {"q": "Sutemizuvchilar yuragida uch tabaqali valf (Trikuspidal klapan) qayerda joylashgan?", "o": ["O'ng bo'lmacha va o'ng qorincha o'rtasida", "Chap bo'lmacha va chap qorincha o'rtasida", "Aorta va chap qorincha o'rtasida", "O'pka arteriyasi kirishida"], "c": 0},
    {"q": "Oqsillarning birlamchi strukturasidagi peptid bog' qaysi guruhlar o'rtasida hosil bo'ladi?", "o": ["Karboksil (-COOH) va Amino (-NH2) guruhlar orasida", "Ikki karboksil guruhi orasida", "Fosfat va riboza orasida", "Gidroksil guruhlar orasida"], "c": 0},
    {"q": "O'simliklarda florigen va auksin yetishmasligi natijasida qanday holat kuzatiladi?", "o": ["Gullash va o'sishning tormozlanishi", "Barglarning sarg'ayishi", "Ildizlarning tez o'sishi", "Mevalarning barvaqt pishishi"], "c": 0},
    {"q": "Xardi-Vaynberg tenglamasining formulasi qanday ko'rinishga ega?", "o": ["p^2 + 2pq + q^2 = 1", "E = mc^2", "PV = nRT", "F = ma"], "c": 0},
    {"q": "Qaysi vitamin yetishmasligi sababli 'Pellagra' (3D kasalligi: dermatit, diareya, demensiya) kelib chiqadi?", "o": ["PP vitamini (Niatsin / B3)", "C vitamini (Askorbin kislotasi)", "B1 vitamini (Tiamin)", "D vitamini (Kalsiferol)"], "c": 0},
    {"q": "Nuklein kislotalarda pirimidin asoslariga qaysilar kiradi?", "o": ["Sitozin, Timin va Urasil", "Adenin va Guanin", "Adenin va Timin", "Guanin va Sitozin"], "c": 0},
    {"q": "Nerv sinapsida neyromediator (masalan, Atsetilxolin) ajralib chiqqach, uni parchalovchi ferment qaysi?", "o": ["Atsetilxolinesteraza", "MAO (Monoaminooksidaza)", "COMT", "Proteaza"], "c": 0},
    {"q": "Odam organizmida o't suyuqligi (safro) qayerda ishlab chiqariladi va qayerda to'planadi?", "o": ["Jigarda ishlab chiqariladi, o't pufagida to'planadi", "O't pufagida ishlab chiqariladi", "Oshqozonda ishlab chiqariladi", "Me'da osti bezida ishlab chiqariladi"], "c": 0},
    {"q": "Hujayra bo'linishida bo'linish urchug'i iplarini izdan chiqaruvchi va mitozni metafazada to'xtatuvchi modda?", "o": ["Kolxitsin", "Penitsillin", "Atropin", "Morfiy"], "c": 0},
    {"q": "Xromosomalarning uchki qismlarini har bir replikatsiyada qisqarib ketishidan saqlaydigan ferment?", "o": ["Telomeraza", "DNK-polimeraza I", "Helikaza", "Topoisomeraza"], "c": 0}
]
