# questions.py ichiga qo'shish uchun:

PART_2_QUESTIONS = [
    {"q": "Genetikada 'epistaz' hodisasi nimani anglatadi?", "o": ["Bir genning boshqa alel bo'lmagan gen ta'sirini bostirishini", "Ikkita alel genning teng namoyon bo'lishini", "Bitta genning bir nechta belgilarga ta'sir ko'rsatishini", "Xromosomalarning o'zaro almashinishini"], "c": 0},
    {"q": "Plazmoliz jarayoni o'simlik hujayrasida qachon kuzatiladi?", "o": ["Hujayra gipertonik eritmaga tushganda", "Hujayra gipotonik eritmaga tushganda", "Hujayra izotonik eritmaga tushganda", "Distillangan suvga solinganda"], "c": 0},
    {"q": "O'simliklarda florigen gormoni qayerda sintezlanadi?", "o": ["Barglarda", "Ildiz uchida", "Meva po'stida", "Tugunchada"], "c": 0},
    {"q": "DNK zanjirida Timin (T) o'rnini RNKda qaysi azotli asos egallaydi?", "o": ["Urasil", "Adenin", "Sitozin", "Guanin"], "c": 0},
    {"q": "Oksidlanishli fosforillanish bosqichida bir molekula НАДH3 H+ dan necha molekula ATF hosil bo'ladi?", "o": ["2.5 (yoki 3)", "1.5 (yoki 2)", "36", "38"], "c": 0},
    {"q": "Bakteriofaglar bu — ...", "o": ["Bakteriyalarni zararlayydigan viruslar", "Fagotsitoz qiluvchi bakteriyalar", "Zamburug' sporalari", "Bir hujayrali sodda hayvonlar"], "c": 0},
    {"q": "Inson qonidagi leykotsitlar orasida eng ko'p ulushni qaysilari egallaydi?", "o": ["Neytrofillar", "Limfotsitlar", "Monotsitlar", "Eozinofillar"], "c": 0},
    {"q": "Sikloz (sitoplazmaning harakati) eukariot hujayrada qaysi strukturalar orqali ta'minlanadi?", "o": ["Mikrofilamentlar va mikrotsayroqlar", "Lizosomalar", "Yadro pardasi", "Ribosomalar"], "c": 0},
    {"q": "Fotosintezning yorug'lik bosqichida suv fotolizi natijasida qaysi gaz ajraladi?", "o": ["Kislorod (O2)", "Karbonat angidrid (CO2)", "Azot (N2)", "Vodorod (H2)"], "c": 0},
    {"q": "Genom mutatsiyasiga misol bo'la oladigan holat qaysi?", "o": ["Aneuploidiya (Xromosomalar sonining o'zgarishi)", "Inversiya", "Translokatsiya", "Nuqtali mutatsiya"], "c": 0},
    {"q": "Buyrak yetishmovchiligida qonda qaysi modda miqdori keskin oshib ketadi?", "o": ["Mochevina va kreatinin", "Glyukoza", "Globin", "Bilirubin"], "c": 0},
    {"q": "T-Xelper leykotsitlarining asosiy vazifasi nima?", "o": ["B-limfotsitlar va T-killerlarni faollashtirish", "Antitelolar sintez qilish", "Fagotsitoz o'tkazish", "Gistamin ajratish"], "c": 0},
    {"q": "Fotosintezning C3 va C4 yo'llari orasidagi asosiy farq nimada?", "o": ["C4 o'simliklarida CO2 dastlab 4 uglerodli kislotaga birikadi", "C3 o'simliklarida yorug'lik bosqichi bo'lmaydi", "C4 o'simliklarida suv fotolizi kechmaydi", "C3 o'simliklari faqat tunda ishlaydi"], "c": 0},
    {"q": "Poliploidiya hodisasi ko'proq qaysi organizmlarda uchraydi va ijobiy natija beradi?", "o": ["O'simliklarda", "Odamlarda", "Sutemizuvchilarda", "Qushlarda"], "c": 0},
    {"q": "Eukariotlarda transkripsiya jarayoni qayerda kechadi?", "o": ["Yadroda", "Sitoplazmada", "Ribosomada", "Golji majmuasida"], "c": 0},
    {"q": "Inson yuragining chap qorinchasidan qaysi qon tomiri chiqadi?", "o": ["Aorta", "O'pka arteriyasi", "Yuqori kovak vena", "Pastki kovak vena"], "c": 0},
    {"q": "Nukleotidlar bir-biri bilan qanday kimyoviy bog' orqali bog'lanib zanjir hosil qiladi?", "o": ["Fosfodieter bog'", "Vodorod bog'", "Peptid bog'", "Disulfid bog'"], "c": 0},
    {"q": "Mitoxondriya va xloroplastlarning kelib chiqishi bo'yicha 'Simbioz nazariya'si nimani ta'kidlaydi?", "o": ["Ular eukariot hujayra ichiga kirib qolgan qadimiy prokariotlardir", "Ular yadro pardasidan hosil bo'lgan", "Ular lizosomadan rivojlangan", "Ular bir hujayrali zamburug'lardir"], "c": 0},
    {"q": "Sitokinlar immun tizimida qanday vazifani bajaradi?", "o": ["Hujayralararo signal beruvchi molekulalar", "Antitelo va antigen kompleksini parchalovchilar", "Kislorod tashuvchilar", "DNK ko'paytiruvchilar"], "c": 0},
    {"q": "Lamarck nazariyasidagi eng asosiy xatolik nimada edi?", "o": ["Loyiha davomida orttirilgan belgilar irsiylanadi degan g'oyasi", "Evolyutsiyani rad etgani", "Turlarning o'zgarmasligini ta'kidlagani", "Tabiiy tanlanishni birinchi bo'lib kashf etgani"], "c": 0},
    {"q": "Pleyotropiya bu — ...", "o": ["Bitta genning bir nechta belgi rivojiga ta'sir qilishi", "Ko'p genlarning bitta belgini idora qilishi", "Xromosomaning yo'qolishi", "Genlar birikkanligi"], "c": 0},
    {"q": "Buyrak usti bezining mag'iz qavatidan qaysi gormonlar ajraladi?", "o": ["Adrenalin va Noradrenalin", "Kortizol va Aldosteron", "Insulin va Glyukagon", "Tiroksin va Kaltsitonin"], "c": 0},
    {"q": "RNK interferensiyasi (RNAi) jarayonining asosiy biologik vazifasi nima?", "o": ["Keraksiz yoki virusli mRNK larni parchalash va genlarni 'o'chirish'", "DNK replikatsiyasini tezlashtirish", "Oqsil sintezini oshirish", "Mutatsiyalarni tuzatish"], "c": 0},
    {"q": "O'simlik to'qimalaridan qaysi biri doimiy bo'linish xususiyatiga ega?", "o": ["Meristema (Hosil qiluvchi to'qima)", "Ksilema", "Floema", "Parenxima"], "c": 0},
    {"q": "Meyoz bo'linish natijasida bitta diployid hujayradan nechta va qanday hujayra hosil bo'ladi?", "o": ["4 ta gaployid hujayra", "2 ta diployid hujayra", "2 ta gaployid hujayra", "4 ta diployid hujayra"], "c": 0},
    {"q": "Sentriolalar qaysi hujayralarda BO'LMAYDI?", "o": ["Yuksak o'simliklar hujayrasida", "Hayvonlar hujayrasida", "Sodda hayvonlarda", "Zamburug'larda"], "c": 0},
    {"q": "Miyoferment myoglobinning va vazifasi nimadan iborat?", "o": ["Mushaklarda kislorod zaxirasini saqlash", "Qonda karbonat angidrid tashish", "Skeletni mustahkamlash", "ATF sintez qilish"], "c": 0},
    {"q": "Inson tanasidagi eukariotik bo'lmagan, lekin hazm qilishda yordam beradigan mikrobioma qayerda eng ko'p joylashgan?", "o": ["Yo'g'on ichakda", "Oshqozonda", "Qizilo'ngachda", "O't pufagida"], "c": 0},
    {"q": "Chastotasi eng yuqori bo'lgan krossingover xromosomaning qaysi qismlarida sodir bo'ladi?", "o": ["Bir-biridan uzoq joylashgan genlar orasida", "Sentromeraga juda yaqin genlarda", "Telomera sohasida", "Giston oqsillarida"], "c": 0},
    {"q": "Nuklein kislota zanjirida gipoxrom va giperxrom effekt nimaga bog'liq?", "o": ["DNK denaturatsiyasi (ikki zanjirning ajralishi)ga", "RNK sinteziga", "Oqsil hosil bo'lishiga", "Ferment ingibirlanishiga"], "c": 0},
    {"q": "Odam organizmida kalsiy miqdorini oshiruvchi gormon qaysi?", "o": ["Paratgormon", "Kaltsitonin", "Tiroksin", "Insulin"], "c": 0},
    {"q": "Autofagiya jarayoni uchun 2016-yilda Nobel mukofoti olgan olim kim?", "o": ["Yoshinori Osumi", "Uotson va Krik", "Yevgeniy Kasperskiy", "Robert Kox"], "c": 0},
    {"q": "O'simlik poyasining yo'g'onlashishi qaysi to'qima hisobiga amalga oshadi?", "o": ["Kambiy", "Epidermis", "Ksilema", "Kork"], "c": 0},
    {"q": "O'roqsimon anemiya kasalligida gemoglobin molekulasida qaysi aminokislota boshqasiga almashib qoladi?", "o": ["Glutamin kislotasi o'rniga Valin", "Lizin o'rniga Alanin", "Prolin o mezonida Serin", "Glitsin o'rniga Leytsin"], "c": 0},
    {"q": "Gipofiz bezining oldingi bo meyoriy qismidan ajralmaydigan gormonni toping.", "o": ["Vasopressin (Orqa bo'lakdan ajraladi)", "Somatotropin", "Prolaktin", "Tireotrop gormon"], "c": 0},
    {"q": "CRISPR-Cas9 texnologiyasi biologiyada qanday maqsadda ishlatiladi?", "o": ["Genomni aniq tahrirlash (kesish va o'zgartirish) uchun", "Oqsillarni sun'iy sintez qilish uchun", "Hujayra bo'linishini tezlashtirish uchun", "Viruslarni ko'paytirish uchun"], "c": 0},
    {"q": "Hujayra membranasining 'Oquvchan-mozaik' modelini kimlar taklif etgan?", "o": ["Singer va Nikolson", "Uotson va Krik", "Shleydan va Shvann", "Robiynson va Braun"], "c": 0},
    {"q": "Spermatogenez jarayonining ko'payish zonasida hujayralar qanday bo'linadi?", "o": ["Mitoz usulida", "Meyoz usulida", "Amitoz usulida", "Bo'linmaydi"], "c": 0},
    {"q": "Gikoliz jarayonining oxirgi mahsuloti nima?", "o": ["Piruvat (Pirouzum kislotasi)", "Atsetil-KoA", "Laktat", "Oksaloatsetat"], "c": 0},
    {"q": "Glyukagon gormonining vazifasi nimadan iborat?", "o": ["Qonda glyukoza miqdorini oshirish (glikogenni parchalash)", "Qonda glyukozani kamaytirish", "Oqsillarni parchalash", "Kalsiyni suyakka yig'ish"], "c": 0},
    {"q": "Sintetik evolyutsion nazariyaning (SEN) boshlang'ich birligi nima hisoblanadi?", "o": ["Populyatsiya", "Alohida individ", "Tur", "Biogeotsenoz"], "c": 0},
    {"q": "Meyozning Pro faza I bosqichida gomologik xromosomalarning birikishi nima deyiladi?", "o": ["Konyugatsiya", "Krossingover", "Translokatsiya", "Interfaza"], "c": 0},
    {"q": "O'simliklarda florigen va giberellinlar qanday jarayonni boshqaradi?", "o": ["Gullash va poya o'sishini", "Barg to'kilishini", "Ildiz chirishini", "Urug'ning uyqu holatini"], "c": 0},
    {"q": "Operon tarkibiga kirmaydigan qismni toping.", "o": ["Intron", "Promotor", "Operator", "Struktura genlari"], "c": 0},
    {"q": "Gemorragik insult nima sababdan yuzaga keladi?", "o": ["Miya qon tomirining yorilishi va qon quyilishi", "Miya tomirining tromblar bilan to'silib qolishi", "Yurak to'xtashi", "Nerv tolasining uzilishi"], "c": 0},
    {"q": "Substratli ingibirlashda ferment aktivligiga nima ta'sir qiladi?", "o": ["Substrat konsentratsiyasining o'ta yuqori bo'lib ketishi", "Haroratning pasayishi", "pH muhitining neytrallashishi", "Mahsulotning yo'qolishi"], "c": 0},
    {"q": "DNK zanjiridagi A+T / G+S nisbati nima deb ataladi?", "o": ["Chargaff qoidasi va Spetsifiklik koeffitsienti", "Mendel nisbati", "Xardi-Vaynberg indeksi", "Morgan birligi"], "c": 0},
    {"q": "Hujayra ichidagi hazm qilish (avtofagiya va geterofagiya) qaysi organoidda kechadi?", "o": ["Lizosoma", "Peroksisoma", "Ribosoma", "Sentrosoma"], "c": 0},
    {"q": "B-limfotsitlar yetilgach, antitelolar ishlab chiqaruvchi qaysi hujayralarga aylanadi?", "o": ["Plazmatik hujayralarga (Plazmotsitlar)", "T-killerlarga", "Makrofaglarga", "Eritrotsitlarga"], "c": 0},
    {"q": "Uotson va Krik tomonidan taklif etilgan B-DNK spiralining bitta to'liq o'ramida necha juft nukleotid bo'ladi?", "o": ["10 juft", "12 juft", "8 juft", "20 juft"], "c": 0}
]
BIOLOGY_QUESTIONS = BIOLOGY_QUESTIONS + ADVANCED_BIOLOGY_QUESTIONS + PART_2_QUESTIONS
# questions.py ichiga qo'shish uchun 3-qism:

PART_3_QUESTIONS = [
    {"q": "Genetikada 'Codominantlik' (hamhukmronlik) hodisasiga qaysi belgi misol bo'ladi?", "o": ["AB (IV) qon guruhi irsiylanishi", "Pushti rangli mo'ynaning paydo bo'lishi", "Mendel noxatlari silliqligi", "Albinizm kasalligi"], "c": 0},
    {"q": "Buyrakda filtrlash jarayoni (birlamchi siydik hosil bo'lishi) qayerda kechadi?", "o": ["Shumlyanskiy-Boumen kapsulasi va kapillyar koptokchasida", "Genle xalqasida", "Yig'uvchi naychalarda", "Buyrak jomida"], "c": 0},
    {"q": "Poyaning birlamchi po'stlog'i va o'tkazuvchi bog'lamlari o'rtasida joylashgan hujayralar qavati nima deyiladi?", "o": ["Peritsikl", "Endoderma", "Epidermis", "Kambiy"], "c": 0},
    {"q": "Glikoliz jarayonida glyukozadan 2 molekula piruvat hosil bo'lishida qaysi ferment asosiy nazorat nuqtasi hisoblanadi?", "o": ["Fosfofruktokinaza (PFK-1)", "Geksokinaza", "Piruvatkinaza", "Aldolaza"], "c": 0},
    {"q": "Ribosomalarda peptid bog' hosil qiluvchi 'Peptidiltransferaza' katalitik aktivligi nimaga tegishli?", "o": ["Katta subbirlikdagi rRNK ga (Riboazim)", "Katta subbirlik oqsillariga", "tRNK molekulasiga", "mRNK ning START kodoniga"], "c": 0},
    {"q": "Nerv tolasida harakat potentsiali (depolyarizatsiya) yuzaga kelganda qaysi ionlar hujayra ichiga shiddat bilan kiradi?", "o": ["Na+ (Natriy) ionlari", "K+ (Kaliy) ionlari", "Cl- (Xlor) ionlari", "Ca2+ (Kalsiy) ionlari"], "c": 0},
    {"q": "Mitoxondriya matritsasida yog' kislotalarining parchalanishi nima deyiladi?", "o": ["Beta-oksidlanish", "Glikoliz", "Krebss sikli", "Glukoneogenez"], "c": 0},
    {"q": "Bakteriyalarda konyugatsiya jarayonida genetik material qaysi organoid/tuzilma orqali o'tadi?", "o": ["Jinsiy pili (F-pili)", "Xivchinlar", "Kapsula", "Mezosoma"], "c": 0},
    {"q": "Prokariotlar va eukariotlar ribosomalarining sedimentatsiya koeffitsientlari qanday?", "o": ["Prokariotlarda 70S, eukariotlarda 80S", "Prokariotlarda 80S, eukariotlarda 70S", "Ikkalasida ham 80S", "Prokariotlarda 50S, eukariotlarda 60S"], "c": 0},
    {"q": "Glyukoneogenez jarayoni asosan qaysi a'zoda kechadi va u nimadan iborat?", "o": ["Jigarda, uglevod bo'lmagan moddalardan glyukoza sintezlanishi", "Mushakda, glikogen parchalanishi", "Buyrakda, protrombin hosil bo'lishi", "Oshqozonda, yog'lar hazm bo meyorida kechishi"], "c": 0},
    {"q": "Immunologiyada 'Antigen taqdim etuvchi hujayralar' (APC) guruhiga qaysilari kiradi?", "o": ["Dendritik hujayralar, makrofaglar va B-limfotsitlar", "T-killerlar va neytrofillar", "Eritrotsitlar va trombotsitlar", "Eozinofillar va bazofillar"], "c": 0},
    {"q": "Paster effekti biologiyada nimani anglatadi?", "o": ["Kislorod borligida achish jarayonining to'xtashi va nafas olishga o'tilishi", "Harorat oshganda fermentlarning inaktivatsiyasi", "Yorug'likda fotosintezning to'xtashi", "Bakteriyalarning sporaga aylanishi"], "c": 0},
    {"q": "O'simliklarda stomatalarning ochilishiga qaysi o'simlik gormoni TERS (yopuvchi) ta'sir ko'rsatadi?", "o": ["Absiz kislotasi (ABA)", "Auksin", "Giberellin", "Sitokinin"], "c": 0},
    {"q": "Xromosomaning krossingover kechmaydigan, zich va transkripsion faol bo'lmagan qismi nima deyiladi?", "o": ["Geteroxromatin", "Euxromatin", "Sentromera", "Promotor"], "c": 0},
    {"q": "Inson tanasidagi eng katta ichki a'zo va eng katta bez qaysi?", "o": ["Jigar", "Oshqozon osti bezi", "Buyrak", "O'pka"], "c": 0},
    {"q": "Meyoz I ning Ana faza I bosqichida qutblarga nima ajraladi?", "o": ["Gomologik xromosomalar (butun holda)", "Xromatidalar (xromosomalar bo'linib)", "Sentriolalar", "Yadro parda bo'laklari"], "c": 0},
    {"q": "Odam organizmida qon ivish jarayonida kaskadli reaksiyalarni faollashtiruvchi ion va vitamin juftligini toping.", "o": ["Ca2+ ionlari va K vitamini", "Fe2+ ionlari va C vitamini", "Na+ ionlari va D vitamini", "Mg2+ ionlari va B12 vitamini"], "c": 0},
    {"q": "Eukariotlarda pre-mRNK dan shpion (cap) va poli-A dum qo'shilishi jarayoni nima deb ataladi?", "o": ["Protsessing (mRNK modifikatsiyasi)", "Transkripsiya", "Translyatsiya", "Splaysing"], "c": 0},
    {"q": "C4 fotosintez yo'lidan foydalanuvchi o'simliklarga qaysi biri kiradi?", "o": ["Makkajo'xori va shakarqamish", "Bug'doy va sholi", "Kartoshka va pomidor", "Qarag'ay va terak"], "c": 0},
    {"q": "Odam miyasida gomeostaz va biologik soatni (sirkad ritm) boshqaruvchi tuzilma qaysi?", "o": ["Gipotalamus (Sipraxiasmatik yadro)", "Miyacha", "Uzunchoq miya", "Gippokamp"], "c": 0},
    {"q": "Sitoplazmatik irsiylanish (onadan o'tish) qaysi organoidlar DNKsi orqali amalga oshadi?", "o": ["Mitoxondriya va Plastidalar", "Lizosoma va Peroksisoma", "Golji majmuasi va EPS", "Ribosoma va Sentrosoma"], "c": 0},
    {"q": "Bakteriya devorini parchalovchi 'Lizozim' fermenti inson tanasida qayerda uchraydi?", "o": ["So'lakda va ko'z yoshida", "Oshqozon shirasida", "Qonda va safroda", "Peshobda"], "c": 0},
    {"q": "DNK zanjirining replikatsiya vilkasida uzuq-juluk sintezlanuvchi orqada qolayotgan zanjir parchalari nima deyiladi?", "o": ["Okazaki bo'laklari", "Intronlar", "Promotorlar", "Transposonlar"], "c": 0},
    {"q": "DNK parchalari (Okazaki bo'laklari)ni o'zaro biriktiruvchi ferment qaysi?", "o": ["DNK-ligaza", "DNK-polimeraza", "Helikaza", "Topoisomeraza"], "c": 0},
    {"q": "O'simliklarda 'CAM-fotosintez' qanday o'simliklarga xos?", "o": ["Kaktus va suvli kserofitlarga (qurg'oqchilik muhitidagilarga)", "Suv o'simliklariga (gidrofitlarga)", "Soya sevuvchi o'simliklarga", "Tundra o'simliklariga"], "c": 0},
    {"q": "Qaysi xastalik monosomiya (2n-1) natijasida kelib chiqadi?", "o": ["Shereshevskiy-Terner sindromi (45, X0)", "Klaynfelter sindromi (47, XXY)", "Daun sindromi (47, +21)", "Patau sindromi (47, +13)"], "c": 0},
    {"q": "Nerv va mushak hujayralarida tinchlik potentsiali (taxminan -70 mV)ni qaysi nasos ushlab turadi?", "o": ["Na+/K+-ATFaza nasosi", "Kalsiy nasosi", "Proton nasosi", "Xlor kanali"], "c": 0},
    {"q": "T-limfotsitlar immun tizimining qaysi organida yetiladi va saralanadi?", "o": ["Timusda (Ayrisimon bez)", "Suyak ko'migi", "Taloq", "Limfa tugunlari"], "c": 0},
    {"q": "Spermatogenezning o'sish zonasida hosil bo'lgan hujayra nima deyiladi?", "o": ["Birinchi tartibli spermatotsit", "Spermatogoniya", "Spermatida", "Spermatozoid"], "c": 0},
    {"q": "Ferment funksiyasida 'Allosterik markaz' nima vazifani bajaradi?", "o": ["Regulyator molekulalar birikib ferment aktivligini o'zgartiradi", "Substrat birikib mahsulotga aylanadi", "Fermentni parchalaydi", "Co-fermentni ushlab turadi"], "c": 0},
    {"q": "Restriksiya fermentlari (Restriktazalar) tabiatda qaysi organizmlarda himoya vositasi hisoblanadi?", "o": ["Bakteriyalarda (bakteriofaglardan himoyalanish uchun)", "Viruslarda", "Zamburug'larda", "O'simliklarda"], "c": 0},
    {"q": "Gormonlardan qaysi biri steroid tuzilishga ega (xolesterindan sintezlanadi)?", "o": ["Kortizol, Testosteron va Estrogen", "Insulin va Glyukagon", "Tiroksin va Triyodtironin", "Adrenalin va Noradrenalin"], "c": 0},
    {"q": "Kollagen oqsili inson tanasida qaysi to'qimaning asosiy strukturni tashkil etadi?", "o": ["Birlashtiruvchi to'qimaning", "Nerv to'qimasining", "Epiteliy to'qimasining", "Mushak to'qimasining"], "c": 0},
    {"q": "O'simlik urug'ining unib chiqishida murtakdagi alfa-amilaza fermentini faollashtiruvchi gormon?", "o": ["Gibberellin", "Absiz kislotasi", "Etilen", "Auksin"], "c": 0},
    {"q": "Ekologiyada 'K-strategiya'ga ega organizmlarga qaysi bir misol bo'ladi?", "o": ["Odam va fillar (kam bolalaydi, uzoq yashaydi)", "Chivin va suvaraklar", "Bakteriyalar", "Bir yillik o'simliklar"], "c": 0},
    {"q": "Photosystem I (PSI) ning reaksion markazi qaysi to'lqin uzunligidagi yorug'likni maksimal yutadi?", "o": ["P700", "P680", "P550", "P450"], "c": 0},
    {"q": "Mitoz bo'linishning qaysi bosqichida xromosomalarning mikroskopda ko'rinishi va sanalishi eng qulay bo'ladi?", "o": ["Metafaza bosqichida", "Profaza bosqichida", "Ana faza bosqichida", "Telofaza bosqichida"], "c": 0},
    {"q": "Onkogenlar bu — ...", "o": ["Mutatsiyaga uchrab saraton (rak) keltirib chiqarishi mumkin bo'lgan genlar", "Faqat viruslarda uchraydigan genlar", "Hujayra o'lishini ta'minlovchi genlar", "Giston oqsillarini kodlovchi genlar"], "c": 0},
    {"q": "Pasterizatsiya jarayoni sterilizatsiyadan nimasi bilan farq qiladi?", "o": ["Suyuqlik 60-80°C gacha qizdiriladi, sporalar saqlanib qoladi", "121°C da avtoklavlanadi", "Barcha spora va bakteriyalar yo'q qilinadi", "Muzlatish orqali amalga oshiriladi"], "c": 0},
    {"q": "Odam organizmida oqsil hazm bo'lishini boshlab beruvchi oshqozon fermenti pepsin qanday muhitda aktiv bo'ladi?", "o": ["Kuchli kislotali muhitda (pH 1.5 - 2.0)", "Neytral muhitda (pH 7.0)", "Ishqoriy muhitda (pH 8.5)", "Kuchsiz ishqoriy muhitda"], "c": 0},
    {"q": "Inson orqa miyasining ko'ndalang kesimida 'kapalak' shaklini hosil qiluvchi qismi nima deyiladi?", "o": ["Kulrang modda (neyron tana va dendritlar)", "Oq modda (aksonlar)", "Orqa miya kanali", "Yumshoq parda"], "c": 0},
    {"q": "DNK zanjirini ochuvchi (vodorod bog'larni uzuvchi) replikatsiya fermenti qaysi?", "o": ["Helikaza", "Ligaza", "Polimeraza", "Primaza"], "c": 0},
    {"q": "Translyatsiya jarayonining boshlanishida (Initiation) birinchi aminokislota qaysi bo'ladi?", "o": ["Metionin (AUG kodoni)", "Lizin", "Valin", "Triptofan"], "c": 0},
    {"q": "Yurak avtomatiyasini ta'minlovchi asosiy birinchi tartibli ritm haydovchisi (paysmeyker) qaysi?", "o": ["Sinus-bo'lmacha tuguni (Sinoatrial tugun)", "Bo'lmacha-qorincha tuguni", "Giss tutami", "Purkinye tolalari"], "c": 0},
    {"q": "O'simliklarda florigen va etilen gormonlarining asosiy vazifasi qanday?", "o": ["Etilen - mevalarni pishiradi, Florigen - gullashni ta'minlaydi", "Etilen - o'sishni tezlashtiradi, Florigen - barg to'kadi", "Ikkisi ham ildiz chiqaradi", "Ikkisi ham uyqu holatiga o'tkazadi"], "c": 0},
    {"q": "Odam organizmida sut kislotasi to'planishi va mushaklar toliqishi qaysi jarayon oqibati?", "o": ["Kislorodsiz glikoliz (anaerob nafas olish)", "Krebss sikli", "Oksidlanishli fosforillanish", "Yog'lar parchalanishi"], "c": 0},
    {"q": "Gemofiliya A kasalligi qaysi qon ivish omilining yetishmasligi sababli kelib chiqadi?", "o": ["VIII omil (Antihemofil globulin)", "IX omil", "X omil", "Fibrinogen"], "c": 0},
    {"q": "Prionlar bu — ...", "o": ["Nuklein kislotasiz, faqat zararlangan oqsildan iborat patogenlar", "Kichik RNK molekulalari", "DNK tutgan viruslar", "Qobiqsiz bakteriyalar"], "c": 0},
    {"q": "O'simlik tanasida suvning pastdan yuqoriga harakatlanishida asosiy tortuvchi kuch nima?", "o": ["Transpiratsiya (barglardan suvning bug'lanishi)", "Ildiz bosimi", "Fotosintez", "Nafas olish"], "c": 0},
    {"q": "Populyatsiya genofondidagi genlar chastotasini tasodifiy o'zgarishi nima deyiladi?", "o": ["Genlar dreyfi (drift)", "Mutatsion bosim", "Tabiiy tanlanish", "Izolatsiya"], "c": 0}
]
# Barcha qismlarni bitta stakka yig'ish
BIOLOGY_QUESTIONS = BIOLOGY_QUESTIONS + ADVANCED_BIOLOGY_QUESTIONS + PART_2_QUESTIONS + PART_3_QUESTIONS
# questions.py ichiga qo'shish uchun 4-qism:

PART_4_QUESTIONS = [
    {"q": "Genetikada 'Codominantlik' holatida geterozigota fenotipi qanday namoyon bo'ladi?", "o": ["Ikkala allelning ham to'liq va bir paytda namoyon bo'lishi bilan", "Aralash (oraliq) fenotip paydo bo'lishi bilan", "Faqat retsessiv belgi namoyon bo'lishi bilan", "Birinchi allelning butunlay yo'qolishi bilan"], "c": 0},
    {"q": "Eukariotlarda rRNK ning ko'pchilik turlari (18S, 28S, 5.8S) yadrocha sohasida qaysi ferment orqali transkripsiyalanadi?", "o": ["RNK-polimeraza I", "RNK-polimeraza II", "RNK-polimeraza III", "DNK-polimeraza alpha"], "c": 0},
    {"q": "Buyrak yetishmovchiligida gemodializ apparatida qon qaysi tamoyil bo'yicha tozalanadi?", "o": ["Yarim o'tkazgich membrana orqali diffuziya va dializ", "Faol transport va ATF sari", "Fagotsitoz jarayoni", "Gidroliz reaksiyasi"], "c": 0},
    {"q": "Qon plazmasidagi osmolyarlikni va onkotik bosimni saqlashda eng katta rol o'ynaydigan oqsil qaysi?", "o": ["Albumin", "Fibrinogen", "Gammaglobulin", "Protrombin"], "c": 0},
    {"q": "Sutemizuvchilar tuxum hujayrasini o'rab turuvchi shaffof parda nima deyiladi?", "o": ["Zona pellucida", "Corona radiata", "Vitellin parda", "Xorion"], "c": 0},
    {"q": "Mitoxondriya ichki membranasi bo'ylab protonlar (H+) harakatida ATF sintez qiluvchi kompleks nima deyiladi?", "o": ["F0F1-ATF-sintaza", "NADH-degidrogenaza", "SitoXrom c-oksidaza", "Suksinatdegidrogenaza"], "c": 0},
    {"q": "O'simliklarda barg to'kilishi va meva uzilishida hujayra devorini parchalovchi fermentlar qaysi gormon ta'sirida faollashadi?", "o": ["Etilen va Absiz kislotasi", "Auksin va Gibberellin", "Sitokinin va Auksin", "Brassinosteroidlar"], "c": 0},
    {"q": "Sitogenetik usulda inson xromosomalari qaysi fazada fiksatsiya qilinadi va tahlil etiladi?", "o": ["Metafaza bosqichida (Kolxitsin qo'llab)", "Profaza bosqichida", "Telofaza bosqichida", "Interfazaning G1 davrida"], "c": 0},
    {"q": "Hujayra siklining G1 va G2 davrlarida nima sodir bo'ladi?", "o": ["G1 - oqsil va RNK sintezi, o'sish; G2 - bo'linishga tayyorgarlik", "G1 - DNK replikatsiyasi; G2 - xromosoma ajralishi", "G1 - yadro parda yo'qolishi; G2 - sentriolalar ajralishi", "Ikkala davrda ham faqat ATF parchalanadi"], "c": 0},
    {"q": "Inson orqa miyasining oldingi shoxlarida joylashgan neyronlar qanday vazifani bajaradi?", "o": ["Harakatlantiruvchi (Motor) neyronlar", "Sezuvchi (Sensorig) neyronlar", "Qo'shimcha (Kirituvchi) neyronlar", "Vegetativ simpatik neyronlar"], "c": 0},
    {"q": "O'simliklarda ikkilamchi ksilema va floema nimadan hosil bo'ladi?", "o": ["Kambiy to'qimasidan", "Protodermadan", "Asosiy meristemadan", "Peritsikldan"], "c": 0},
    {"q": "Prokariotlarda DNK transkripsiyasini boshlash uchun RNK-polimerazaga qaysi omil (subbirlik) birikishi kerak?", "o": ["Sigma-omil (σ-factor)", "Rho-omil (ρ-factor)", "TATA-fakor", "TIF2-omil"], "c": 0},
    {"q": "Eukariotlarda gen ekspressiyasining eng birinchi darajadagi boshqarilishi qayerda kechadi?", "o": ["Xromatin modifikatsiyasi (Asetillanish va Metillanish) darajasida", "Splaysing darajasida", "Translyatsiya darajasida", "Post-translyatsiya darajasida"], "c": 0},
    {"q": "Genetikada 'Maternal effekt' (onadorlik effekti) nimaga bog'liq?", "o": ["Tuxum hujayra sitoplazmasida to'plangan mRNK va oqsillarga", "Yadroviy genlar o'zaro birikishiga", "Otadan o'tadigan Y-xromosomaga", "Faqat atrof-muhit haroratiga"], "c": 0},
    {"q": "Qaysi xromosoma mutatsiyasida xromosomaning muayyan qismi 180 darajaga burilib qayta birikadi?", "o": ["Inversiya", "Duplikatsiya", "Deletsiya", "Translokatsiya"], "c": 0},
    {"q": "Nerv tolasida Mielin qobig'ini periferik nerv sistemasida qaysi hujayralar hosil qiladi?", "o": ["Shvann hujayralari (Lemmotsitlar)", "Oligodendrotsitlar", "Astrotsitlar", "Mikrogiya hujayralari"], "c": 0},
    {"q": "Sutemizuvchilar o'pkasida gaz almashinuvi kechadigan asosiy struktur birlik?", "o": ["Alveolalar", "Bronxiolalar", "Tratheyalar", "Plevra bo'shlig'i"], "c": 0},
    {"q": "Glukoneogenez jarayonida piruvatdan oksaloatsetat hosil qiluvchi ferment qaysi?", "o": ["Piruvatkarboksilaza", "Piruvatkinaza", "Laktatdegidrogenaza", "Fosfoenolpiruvatkarboksikinaza"], "c": 0},
    {"q": "Bakteriyalarda peptidoglikan (murein) sintezini tormozlovchi va ularni parchalovchi antibiotik guruh?", "o": ["Penitsillinlar va Tsefalosporinlar", "Tetratsiklinlar", "Streptomitsinlar", "Xloramfenikol"], "c": 0},
    {"q": "Yurak siklining umumiy pauza (bo'lmacha va qorinchalar diastolasi) davri qancha davom etadi?", "o": ["0.4 sekund", "0.1 sekund", "0.3 sekund", "0.8 sekund"], "c": 0},
    {"q": "Fotosintezning yorug'lik reaksiyalarida e- o'tkazuvchi Z-sxema bo'ylab electron qayerdan qayerga uzatiladi?", "o": ["Suvdan NADP+ ga", "NADP+ dan suvga", "CO2 dan glyukozaga", "ATF dan xlorofillga"], "c": 0},
    {"q": "O'simliklarda 'Guttatsiya' hodisasi nima va u qaysi a'zo orqali kechadi?", "o": ["Suyuq suv tomchilarining gidatodalar (suv teshikchalari) orqali ajralishi", "Bug' holatidagi suvning ustitsadan chiqishi", "Shira ajralishi", "Ildiz orqali suv so'rilishi"], "c": 0},
    {"q": "Odam organizmida qon hosil bo'lishi (Gematopoez) katta yoshlilarda qayerda kechadi?", "o": ["Qizil suyak ko'migida", "Sariq suyak ko'migida", "Jigarda", "Taloq pulpasida"], "c": 0},
    {"q": "Xromosomaning sentromera sohasida joylashgan va bo'linish urchug'i iplari birikadigan oqsilli disk?", "o": ["Kinetoxor", "Nukleosoma", "Telomera", "Astrotsit"], "c": 0},
    {"q": "Prion kasalliklariga misol bo'ladigan xastalikni toping.", "o": ["Kreytsfeldt-Yakob kasalligi va Kuru", "Altsgeymer kasalligi", "Parkinson kasalligi", "G Huntington kasalligi"], "c": 0},
    {"q": "DNK molekulasida Guanin (G) va Sitozin (S) orasida nechta vodorod bog'i bo'ladi?", "o": ["3 ta vodorod bog'i", "2 ta vodorod bog'i", "1 ta vodorod bog'i", "4 ta vodorod bog'i"], "c": 0},
    {"q": "Inson ko'zidagi to'r pardada joylashgan 'Sariq dog' (Fovea centralis) sohasida qaysi retseptorlar ko'p bo'ladi?", "o": ["Faqat kolbachasimon hujayralar (Kolbochkalar)", "Faqat tayyoqchasimon hujayralar", "Ikkalasi ham teng", "Retseptorlar bo'lmaydi"], "c": 0},
    {"q": "Oqsillarning uchlamchi va to'rtlamchi strukturasi buzilishi lekin birinchi darajali peptid bog'ining saqlanib qolishi nima deyiladi?", "o": ["Qaytuvchan denaturatsiya", "Qaytmas denaturatsiya", "Renaturatsiya", "Proteoliz"], "c": 0},
    {"q": "Restriksiya fermentlari yordamida kesilgan DNK bo'laklarining yopishqoq uchlari qanday xususiyatga ega?", "o": ["Komplementar bir zanjirli ketma-ketlikka ega bo'ladi", "To'g'ri (kallakli) kesilgan bo'ladi", "Faqat A-T juftliklaridan iborat bo'ladi", "Faqat RNK dan iborat bo'ladi"], "c": 0},
    {"q": "Bakteriyalarning sporasi nima uchun xizmat qiladi?", "o": ["Noqulay atrof-muhit sharoitlaridan saqlanish uchun", "Ko'payish va tarqaliish uchun", "Oziq-ovqat zaxirasini to'plash uchun", "Hujayralararo aloqa uchun"], "c": 0},
    {"q": "Krebss siklida hosil bo'ladigan va nafas olish zanjiriga uzatiladigan qaytarilgan kofermentlar qaysilar?", "o": ["NADH va FADH2", "NADP H va ATF", "Piruwat va Laktat", "KoA va Atsetat"], "c": 0},
    {"q": "Autofagosoma bilan lizosoma qo'shilishi natijasida hosil bo'ladigan organoid?", "o": ["Autolizosoma (Autofagolizosoma)", "Peroksisoma", "Birlamchi lizosoma", "Geterofagosoma"], "c": 0},
    {"q": "Inson miyasining qaysi bo'limida nafas olish, yutish va qon tomirlar markazi joylashgan?", "o": ["Uzunchoq miyada (Medulla oblongata)", "Miyachada", "O'rta miyada", "Oraliq miyada"], "c": 0},
    {"q": "O'simliklarda 'Tropizm' va 'Nastiya' harakatlarining asosiy farqi nimada?", "o": ["Tropizm - yo'naltirilgan ta'sirga javob; Nastiya - yo'nalishsiz ta'sirga javob", "Tropizm - tez harakat; Nastiya - sekin harakat", "Tropizm - faqat ildizda; Nastiya - faqat mevalarda", "Ikkalasi ham bir xil jarayon"], "c": 0},
    {"q": "Gipofiz bezining orqa bo'lagidan ajraladigan Vasopressin (Antidiuretik gormon - ADG) ning asosiy funksiyasi?", "o": ["Buyrak nefronlarida suv reabsorbsiyasini oshirish", "Siydik miqdorini ko'paytirish", "Qonda kalsiyni kamaytirish", "Glikogen sintezini tezlashtirish"], "c": 0},
    {"q": "Viruslar hujayraga kirganda ularning kapsid oqsillaridan xalos bo'lishi nima deyiladi?", "o": ["Yechilish (Uncoating)", "Adsorbsiya", "Penetratsiya", "Maturatsiya"], "c": 0},
    {"q": "Polimeraza zanjir reaksiyasida (PZR) DNK zanjirlarini ajratish uchun qanday harorat qo'llaniladi?", "o": ["94-95 °C (Denaturatsiya bosqichi)", "50-60 °C", "72 °C", "37 °C"], "c": 0},
    {"q": "Odam so'lagida joylashgan va kraxmalni disaxaridlarga parchalovchi ferment?", "o": ["Ptiyalin (Tuklik alfa-amilaza)", "Pepsin", "Tiripsin", "Lipaza"], "c": 0},
    {"q": "O'simliklarda murtak xaltasi (megasporogenez) natijasida necha o'zakli struktura hosil bo meyor bo'ladi?", "o": ["8 o'zakli murtak xaltasi", "4 o'zakli murtak xaltasi", "2 o'zakli murtak xaltasi", "16 o'zakli murtak xaltasi"], "c": 0},
    {"q": "Meyozda krossingover kechgandan so'ng gomologik xromosomalarning bir-biriga teshilishi/birikib turish nuqtasi nima deyiladi?", "o": ["Xiazma", "Sentromera", "Kinetoxor", "Nukleosoma"], "c": 0},
    {"q": "Sutemizuvchilar yuragida uch tabaqali valf (Trikuspidal klapan) qayerda joylashgan?", "o": ["O'ng bo'lmacha va o'ng qorincha o'rtasida", "Chap bo'lmacha va chap qorincha o meyorida", "Aorta va chap qorincha o'rtasida", "O'pka arteriyasi kirishida"], "c": 0},
    {"q": "Oqsillarning birlamchi strukturasidagi peptid bog' qaysi guruhlar o'rtasida hosil bo'ladi?", "o": ["Karboksil (-COOH) va Amino (-NH2) guruhlar orasida", "Ikki karboksil guruhi orasida", "Fosfat va riboza orasida", "Gidroksil guruhlar orasida"], "c": 0},
    {"q": "O'simliklarda florigen va auksin yetishmasligi natijasida qanday holat kuzatiladi?", "o": ["Gullash va o'sishning tormozlanishi", "Barglarning sarg'ayishi", "Ildizlarning tez o'sishi", "Mevalarning barvaqt pishishi"], "c": 0},
    {"q": "Xardi-Vaynberg tenglamasining formulasi qanday ko'rinishga ega?", "o": ["p^2 + 2pq + q^2 = 1", "E = mc^2", "PV = nRT", "F = ma"], "c": 0},
    {"q": "Qaysi vitamin yetishmasligi sababli 'Pellagra' (3D kasalligi: dermatit, meyor, demensiya) kelib chiqadi?", "o": ["PP vitamini (Natsin / B3)", "C vitamini (Askorbin kislotasi)", "B1 vitamini (Tiamin)", "D vitamini (Kalsiferol)"], "c": 0},
    {"q": "Nuklein kislotalarda pimidin asoslariga qaysilar kiradi?", "o": ["Sitozin, Timin va Urasil", "Adenin va Guanin", "Adenin va Timin", "Guanin va Sitozin"], "c": 0},
    {"q": "Nerv sinapsida neyromediator (masalan, Atsetilxolin) ajralib chiqqach, uni parchalovchi ferment qaysi?", "o": ["Atsetilxolinesteraza", "MAO (Monoaminooksidaza)", "COMT", "Proteaza"], "c": 0},
    {"q": "Odam organizmida o't suyuqligi (safro) qayerda ishlab chiqariladi va qayerda to'planadi?", "o": ["Jigarda ishlab chiqariladi, o't pufagida to'planadi", "O't pufagida ishlab chiqariladi", "Oshqozonda ishlab chiqariladi", "Me'da osti bezida ishlab chiqariladi"], "c": 0},
    {"q": "Hujayra bo'linishida bo'linish urchug'i iplarini izdan chiqaruvchi va mitozni metafazada to'xtatuvchi modda?", "o": ["Kolxitsin", "Penitsillin", "Atropin", "Morfiy"], "c": 0},
    {"q": "Xromosomalarning uchki qismlarini har bir replikatsiyada qisqarib ketishidan saqlaydigan ferment?", "o": ["Telomeraza", "DNK-polimeraza I", "Helikaza", "Topoisomeraza"], "c": 0}
]
# Barcha qismlarni bitta stakka yig'ish
BIOLOGY_QUESTIONS = (
    BIOLOGY_QUESTIONS + 
    ADVANCED_BIOLOGY_QUESTIONS + 
    PART_2_QUESTIONS + 
    PART_3_QUESTIONS + 
    PART_4_QUESTIONS
)
